image: Visual Studio 2017
configuration: Release
platform:
  - Win32
  - x64

install:
  ## Set up nasm
  - choco install nasm
  - set PATH=%PATH%;"C:\Program Files\NASM"
  ## Set up libpng
  - cd C:\Tools\vcpkg
  - vcpkg install libpng:x86-windows
  - vcpkg install libpng:x64-windows
  ## Prepare cmake
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir cmake_build

before_build:
  - cmake --version
  - cd cmake_build
  - cmake .. -DWITH_CRT_DLL=1 -DREQUIRE_SIMD=1 -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - msbuild cmake_build\mozjpeg.sln

artifacts:
 - path: cmake_build\**\Release\**\*.exe
 - path: cmake_build\**\Release\**\*.lib

cache:
  - C:\ProgramData\chocolatey\bin
  - C:\ProgramData\chocolatey\lib
  - C:\Program Files\NASM
  - c:\tools\vcpkg\installed\
