name: Build static on linux

on:
  release:
    types: [published, prereleased]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: update
        run: sudo apt update
      - name: install deps
        run: sudo apt install autoconf libtool nasm libpng-dev automake pkg-config build-essential -yq
      - name: list versions
        run: |
          nasm -v
          cmake --version
          git describe --always --tags --dirty
          GIT_VERSION=$(git describe --always --tags --dirty)
      - name: Build static
        run: |
          cmake -B static -DENABLE_SHARED=0 -DENABLE_STATIC=1 -DREQUIRE_SIMD=1
          cmake --build static --config Release
      - name: Zip release
        run: |
          mkdir Release
          mv static/*-static ./Release
          7z a mozjpeg-$GIT_VERSION-linux-x64.zip Release
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mozjpeg-$GIT_VERSION-linux-x64.zip
          path: |
            .Release/
